# Generated by Django 4.2.10 on 2024-03-15 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_management', '0009_appointment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='profilepic',
            new_name='profile_pic',
        ),
    ]
